### ISSUE TITLE
Dalamud error while trying to run the game with plugin enabled.

### ISSUE THREAD

**Issue by E-Ballard** [arcsidian/XivVoices#1]
---------------------------
Dalamud
---------------------------
An internal error in a Dalamud plugin occurred.
The game must close.

DirectoryNotFoundException
System.Private.CoreLib, Microsoft.Win32.SafeHandles.SafeFileHandle::CreateFile

Plugin that caused this:
Xiv Voices

Click "Yes" and remove it.

More information has been recorded separately.

Do you want to disable all plugins the next time you start the game?
---------------------------
Yes   No   
---------------------------

**Comment by arcsidian** [comment]
Fixed in 0.2.3.0
If a similar crash happens again, please get the dalamud logs before pressing (yes/no) and include it in a new issue
Dalamud logs can be found in: C:\Users\USER\AppData\Roaming\XIVLauncher
