### ISSUE TITLE
[Suggestion] Decouple Updates Download UI from Settings UI

### ISSUE THREAD

**Issue by GotekSC** [arcsidian/XivVoices#4]
While updates are downloading, you can't access the settings gui.

Was assembling my raid party, setting up stream etc and had local tts on from the last time I played. Party members trolled me while I could only sit it out :)

I think it would be a great idea of decoupling the update ui from the settings ui to remedy this.

**Comment by arcsidian** [comment]
Sorry about that lol, I was actually watching your stream when it happened, it was funny. I will make sure to fix that in the next update.

**Comment by GotekSC** [comment]
haha wow, did eliz tell you to watch the pain

**Comment by arcsidian** [comment]
yup!

**Comment by GotekSC** [comment]
I see this is already implemented. Thanks again arc.
