### ISSUE TITLE
[Suggestion] Whitelist Specific Characters For Local TTS

### ISSUE THREAD

**Issue by GotekSC** [arcsidian/XivVoices#5]
It would be awesome if we could whitelist specific PC's for the Local TTS feature. To only have it on for people we trust not to mess with the XIVVoices user.

Maybe modeling it after the syntax for `/tell` ingame would be a good idea.

`/tell [PC name]@[World name] [message]`
https://ffxiv.consolegameswiki.com/wiki/Chat_text_commands

**Comment by arcsidian** [comment]
I've been thinking about this, this will happen eventually once I make full use of the playerData.json that I created recently, Right now this json can be found in your XIVV folder which saves any friend you interact with who was in close proximity enough to have their model data saved. So later this can be used to give each friend their own Local TTS voice, and I will plan on updating it so you can edit it in UI, make your own whitelist..etc

**Comment by GotekSC** [comment]
Sounds cool, thanks for letting me know.
