### ISSUE TITLE
[Suggestion] Allow Power Users To Change XIV_Voices Directory

### ISSUE THREAD

**Issue by GotekSC** [arcsidian/XivVoices#6]
I assume the choice to force to a root of a disk comes from either of:

1. 256 character limit in Windows filepaths
2. Permissions issues with `C:\Program Files (x86)` and `C:\Program Files`

The 256 character limit of filepaths in windows can be disabled with
`Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
`
As per https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

I would love to be able to have my drive like this, with `LongPathsEnabled = 1`:

```
F:/
└─ local
   └─ games
      ├─ steam
      └─ various
         ├─ final-fantasy-xiv-a-realm-reborn
         ├─ final-fantasy-xiv-mods
         └─ final-fantasy-xiv-xivvoices
```
Would it be possible to implement an option to change the `XIV_Voices` directory **location and name** hidden away behind _"Advanced User"_ settings or something?

**Comment by arcsidian** [comment]
I can add that feature as for advanced users if you want, but unfortunately C:/XIV_Voices/Tools still has to exist in that place in order for LocalTTS to load correctly.

**Comment by GotekSC** [comment]
Hmm, okay. I guess then it does not make too much sense, at least for my usecase. It's pretty much about keeping root directory of drives as clean as possible. If its not reasonable to also have `C:/XIV_Voices/Tools` changeable, then I think you can save the effort of doing it halfway.

**Comment by arcsidian** [comment]
I'm still trying to find a solution, the LocalTTS library depends on yet another DLL that has to have a static path, you can see it here:

https://github.com/arcsidian/XivVoices/blob/main/XivVoices/LocalTTS/TTSNative.cs

**Comment by livvydoodlez** [comment]
This still needs to be worked on.

I cannot change the directory what so ever of XIVV and I do not have any room on my C: Drive to use the add-on.

**Comment by arcsidian** [comment]
Unfortunately, as explained in Discord a few weeks ago, this plugin has ceased further development due to personal reasons, everyone is welcome to fork it and continue its development themselves, or try a different plugin called [Artemis ](https://github.com/Sebane1/RoleplayingVoiceDalamud)which does a similar job to XIVV (but online instead of local) and it also has all of XIVV's files.
