### ISSUE TITLE
crashes the whole game

### ISSUE THREAD

**Issue by jchai002** [arcsidian/XivVoices#7]
I love the voices, but it crashes the entire game after a few seconds in the cut scene. 
No error messages, just shuts down the game.

**Comment by arcsidian** [comment]
The latest version should have fixed this issue, but in case it still happens, please provide dalamud logs in discord the moment this crash happens again so I can find out the reason behind the crash and fix it. (Make sure to send that dalamud.log file before reopening the game, you can find its location in the xivv-bugs channel's pins)
